
services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    networks:
      - speech_net
    volumes:
      - logs:/var/log/app
    env_file: 
      - .env
    environment:
      - HOST=${HOST}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - LOG_DIR=/var/log/app
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - asr
      - tts
    restart: unless-stopped
  tts:
    build:
      context: ./tts-service
      dockerfile: Dockerfile
    networks:
      - speech_net
    volumes:
      - models_tts:/opt/models
      - logs:/var/log/app
    env_file:
      - .env
    environment:
      - HOST=${HOST}
      - TTS_PORT=${TTS_PORT}
      - LOG_DIR=/var/log/app
    ports:
      - "${TTS_PORT}:${TTS_PORT}"
    restart: unless-stopped

  asr:
    build: 
      context: ./asr-service
      dockerfile: Dockerfile
    container_name: asr
    networks:
      - speech_net
    volumes:
      - models_asr:/opt/models
      - logs:/var/log/app
    env_file:
      - .env
    environment:
      - HOST=${HOST}
      - ASR_PORT=${ASR_PORT}
    ports:
      - "${ASR_PORT}:${ASR_PORT}"
    restart: unless-stopped


networks:
  speech_net:
    driver: bridge


volumes:
  models_asr:
  models_tts:
  logs: