
services:
  tts:
    build:
      context: ./tts-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8082"
    volumes:
      - models_tts:/opt/models
    restart: unless-stopped

  asr:
    build: 
      context: ./asr-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - models_asr:/opt/models
    restart: unless-stopped


  

volumes:
  models_tts:
    name: models_tts
  models_asr:
    name: models_asr